/*
 * Copyright (C) 2008 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.common.testing.junit4;

import junit.framework.AssertionFailedError;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.regex.MatchResult;

/**
 * Unit test for {@link JUnitAsserts}.
 *
 * @author kevinb
 */
@RunWith(JUnit4.class)
public class JUnitAssertsTest {

  @Test
  public void testNotEqualSuccess() {
    JUnitAsserts.assertNotEqual(1, 2);
  }

  @Test
  public void testNotEqualNullSuccess1() {
    JUnitAsserts.assertNotEqual(null, 2);
  }

  @Test
  public void testNotEqualNullSuccess2() {
    JUnitAsserts.assertNotEqual(1, null);
  }

  @Test
  public void testNotEqualFailure() {
    try {
      JUnitAsserts.assertNotEqual(1, 1);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("expected not to be:<1>", e.getMessage());
    }
  }

  @Test
  public void testNotEqualNullFailure() {
    try {
      JUnitAsserts.assertNotEqual(null, null);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "expected not to be:<null>", e.getMessage());
    }
  }

  @Test
  public void testMessageReturnedByNotEqualFailure() {
    try {
      JUnitAsserts.assertNotEqual("foo", 1, 1);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "foo expected not to be:<1>", e.getMessage());
    }
  }

  @Test
  public void testMatchesRegexSuccess() {
    MatchResult result = JUnitAsserts.assertMatchesRegex("a(.)", "ab");
    Assert.assertEquals("b", result.group(1));
  }

  @Test
  public void testMatchesRegexFailure() {
    try {
      JUnitAsserts.assertMatchesRegex("thing", "a(.)", "ace");
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected to match regex:<a(.)> but was:<ace>",
          e.getMessage());
    }
  }

  @Test
  public void testMatchesRegexFailureNull() {
    try {
      JUnitAsserts.assertMatchesRegex("thing", "a(.)", null);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected to match regex:<a(.)> but was:null",
          e.getMessage());
    }
  }

  @Test
  public void testContainsRegexSuccess() {
    MatchResult result = JUnitAsserts.assertContainsRegex("a(.)", "ace");
    Assert.assertEquals("c", result.group(1));
  }

  @Test
  public void testContainsRegexFailure() {
    try {
      JUnitAsserts.assertContainsRegex("thing", "a(.)", "ha");
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected to contain regex:<a(.)> but was:<ha>",
          e.getMessage());
    }
  }

  @Test
  public void testContainsRegexFailureNull() {
    try {
      JUnitAsserts.assertContainsRegex("thing", "a(.)", null);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected to contain regex:<a(.)> but was:null",
          e.getMessage());
    }
  }

  @Test
  public void testNotMatchesRegexSuccess() {
    JUnitAsserts.assertNotMatchesRegex("a(.)", "ace");
  }

  @Test
  public void testNotMatchesRegexFailure() {
    try {
      JUnitAsserts.assertNotMatchesRegex("thing", "a(.)", "ab");
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected not to match regex:<a(.)> but was:<ab>",
          e.getMessage());
    }
  }

  @Test
  public void testNotContainsRegexSuccess() {
    JUnitAsserts.assertNotContainsRegex("a(.)", "ha");
  }

  @Test
  public void testNotContainsRegexFailure() {
    try {
      JUnitAsserts.assertNotContainsRegex("thing", "a(.)", "ace");
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "thing expected not to contain regex:<a(.)> but was:<ace>",
          e.getMessage());
    }
  }

  @Test
  public void testContentsInOrderSuccess() {
    List<Integer> actual = Arrays.asList(1, 2, 3);
    JUnitAsserts.assertContentsInOrder(actual, 1, 2, 3);
  }

  @Test
  public void testContentsInOrderEmptySuccess() {
    List<Integer> actual = Collections.emptyList();
      JUnitAsserts.assertContentsInOrder(actual);
  }

  @Test
  public void testContentsInOrderEmptyFailureEmptyActual() {
    List<Integer> actual = Collections.emptyList();
    try {
        JUnitAsserts.assertContentsInOrder("foo", actual, 1);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "foo expected:<[1]> but was:<[]>", e.getMessage());
    }
  }

  @Test
  public void testContentsInOrderEmptyFailureEmptyExpected() {
    List<Integer> actual = Collections.singletonList(1);
    try {
      JUnitAsserts.assertContentsInOrder("foo", actual);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "foo expected:<[]> but was:<[1]>", e.getMessage());
    }
  }

  @Test
  public void testContentsInOrderFailureDueToOrder() {
    List<Integer> actual = Arrays.asList(1, 2);
    try {
      JUnitAsserts.assertContentsInOrder("foo", actual, 2, 1);
      Assert.fail("no exception thrown");
    } catch (AssertionFailedError e) {
      Assert.assertEquals("failure message generated by MoreAsserts",
          "foo expected:<[2, 1]> but was:<[1, 2]>", e.getMessage());
    }
  }
}
